security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            http_basic:
                realm: Secured Area
            custom_authenticator: App\Security\LoginFormAuthenticator
            # Accès refusé à un visiteur : redirection vers le formulaire de connexion
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/product, roles: ROLE_ADMIN }
        - { path: ^/category, roles: ROLE_ADMIN }
        - { path: ^/jour, roles: ROLE_ADMIN }
        - { path: ^/synthese/1, roles: ROLE_ADMIN }
        - { path: ^/synthese/2, roles: ROLE_ADMIN }
        - { path: ^/synthesepoids, roles: ROLE_ADMIN }
        # - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/settings, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/livree, roles: ROLE_ADMIN }
        - { path: ^/livraison, roles: ROLE_ADMIN }
        - { path: ^/recap, roles: ROLE_ADMIN }

